### ISSUE TITLE
Move docs from GH wiki to repo for better organization/cross-referencing abilities

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#105]
The GitHub wiki has a pretty minimal list of features. We will be able to do a lot more if we move the contents of the wiki into a `docs` folder in the repository itself.

**Comment by moshner** [comment]
Maybe I should start working on this again... :(

Would you like to upload the document with all the block textures?

**Comment by chimericdream** [comment]
I should be able to do that this weekend, yeah.
