### ISSUE TITLE
Lava Sponge mod

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#111]
I like the idea of being able to use sponges in the nether. Even better would be if someone (probably me, in a bajillion years) made a similar add-on to this as the Better Sponge Absorption Radius by Serilum. :-)

https://www.curseforge.com/minecraft/mc-mods/lavasponge

**Comment by moshner** [comment]
I wanna say that the ring of sponge works on lava.

**Comment by chimericdream** [comment]
Ah, good to know.

**Comment by chimericdream** [comment]
I don't think it deletes fluids, but I can check tonight.
