### ISSUE TITLE
Spawn eggs put into spawner convert to the original spawner type

### ISSUE THREAD

**Issue by moshner** [worldofpannotia/minecraft-modpack#117]
I put my very rare wither skeleton spawn egg in a former blaze spawner. It turned into a blaze spawner and the egg became a blaze egg. 

Oops!

I'd like to see if we can cheat in my wither skeleton egg back and fix this bug. :)

**Comment by chimericdream** [comment]
Fixed in 8.3.0. Next time I get online, I'll put a wither skeleton spawn egg in your storage system.
