### ISSUE TITLE
Recipe conflict with Wither Bones

### ISSUE THREAD

**Issue by moshner** [worldofpannotia/minecraft-modpack#120]
![2021-05-03_17 38 17](https://user-images.githubusercontent.com/3300206/116942106-900e4d80-ac36-11eb-8753-6547fd6adfe4.png)

It should convert to the other wither bone but it's conflicting with "Wither Bone Meal" which was a thing that I didn't know about.

**Comment by chimericdream** [comment]
Fixed in 8.3.0
