### ISSUE TITLE
Cannot right click to add seeds to quark seed pouch

### ISSUE THREAD

**Issue by moshner** [worldofpannotia/minecraft-modpack#121]
v8.2.1

**Comment by moshner** [comment]
tested: wheat seeds, sugar cane seeds, beetroot seeds, cabbage seeds, pineapple seeds, and cactus seeds. All not working

**Comment by chimericdream** [comment]
It looks like this is a known bug in Quark right now. Specifically, it seems to be a conflict between Mouse Tweaks and Quark.

https://github.com/Vazkii/Quark/issues/3041
