### ISSUE TITLE
Loot table changes

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#136]
Given the number of mods we have in the pack that add items to Minecraft's built in loot tables and which _also_ add custom dungeons and/or structures, we should look at the different loot tables and cross-pollinate items between them.

This ticket is meant to be a place for discussion and research to figure out what changes we want to make. The actual work should be split into separate tickets. The main reason for splitting things into separate tickets is that it will allow us to make the changes piecemeal and not worry about situations like what I have seen with the Rings of Ascension, where the rings were not added to modded loot tables no matter what I did.

_Note: The following lists are not yet complete._

#### Mods that add dungeons or other structures with loot tables
* Dungeons Plus
* Buzzier Bees

#### Mods that add things to vanilla loot tables and/or their own structures
* Rings of Ascension
* Quark

**Comment by moshner** [comment]
rings everywhere!

**Comment by chimericdream** [comment]
Quark colored runes

**Comment by moshner** [comment]
Normalize dungeons between vanilla and modded loot

**Comment by moshner** [comment]
Make RS part of the rare loot for something

**Comment by moshner** [comment]
Add Immolation blades to bastions/nether fortress loot

**Comment by chimericdream** [comment]
> rings everywhere!

#planned

100% chance of ring of flight x3 in every desert temple, ocean ruin, vanilla dungeon, and blacksmith house

**Comment by moshner** [comment]
Any more changes planned?

**Comment by chimericdream** [comment]
I haven't actually made changes to any loot tables thus far. I agree that we could use more questing, though, so I should probably come back to this and come up with a concrete list of proposed additions (specific items + locations). We can always build more quests later (maybe even see if an RPG-style quest mod exists), but you have to start somewhere.
