### ISSUE TITLE
Remove "Random Village Names mod" (was: Game lags when entering/leaving village)

### ISSUE THREAD

**Issue by moshner** [worldofpannotia/minecraft-modpack#138]
When the message pops up that you are entering or leaving a village area I've found that the game lags a bit. It makes it a bit odd when trying to loot....i mean visit....villages.

**Comment by chimericdream** [comment]
Confirmed. I saw a bug report related to the Random Village Names mod by Serilum that it apparently is the root cause. Since it just provides ambience, I'm fine removing it.
