### ISSUE TITLE
Chipped mod

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#142]
This is essentially a successor to the Chisel mod that we've had in the past. I know we already have Chisels & Bits along with some others that add block variants, so this may not make the cut. But I came across it and loved the aesthetic (_especially_ the different workbenches they add).

https://www.curseforge.com/minecraft/mc-mods/chipped

https://www.curseforge.com/minecraft/mc-mods/chipped/screenshots

**Comment by moshner** [comment]
Love it!
