### ISSUE TITLE
Smelting compressed blocks

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#145]
This is a recipe idea inspired by [a 1.12 datapack](https://www.curseforge.com/minecraft/customization/smeltable-compressed-blocks) I saw. Essentially, we could add smelting recipes for the compressed variants of things like cobblestone, stone, sand, etc. It wouldn't/shouldn't necessarily be 1:1 output, but it could speed things up for times when we want to make a _lot_ of some smelted item.

Examples:
Block | 1x compressed | 2x compressed | 3x compressed
------------ | ------------- | ------------- | -------------
Cobblestone | 9 stone | 64 stone | 64 stone bricks
Sand | 9 glass | 64 glass | —
Netherrack | 9 nether bricks | 64 nether bricks | 64 nether brick blocks
more? | — | — | —

**Comment by moshner** [comment]
Seems like a lot of work. You can add it if you like but I don't see a ton of benefit

**Comment by chimericdream** [comment]
Maybe for 9.x or if I get bored, but I agree. That's also part of why I haven't really moved on this one in awhile.
