### ISSUE TITLE
Netherite armor/tool variants

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#146]
This is an interesting idea. If we wanted to add this, I would probably advocate for disabling the "ultimate" tier, which combines all the variants into one. That way we'd still have some motivation for using the different kinds.

https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite

Of course, most (maybe all) of the effects are probably added by either one of the Rings of Ascension, a totem, or a modded enchantment. So this might not provide much more than aesthetic variants. If that's the case, we could always request permission to re-use the textures in a resource pack and add our own variants (via ContentTweaker) that don't change stats but just use a different texture.

**Comment by chimericdream** [comment]
Maybe for a later version of the pack. I don't think we need this in 8.x.

**Comment by moshner** [comment]
Meh. Looks cool but maybe 9x
