### ISSUE TITLE
Enchanting table rerolls

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#148]
Hate having to burn through books just to get the enchants you want on an item? This mod helps with that. It can be configured to require XP and/or lapis to trigger a re-roll of the current list of enchants without needing to actually enchant another item in between.

https://www.curseforge.com/minecraft/mc-mods/reroll-forge

**Comment by moshner** [comment]
Meh, it's probably too late for this pack. Maybe version 9?

**Comment by chimericdream** [comment]
Agreed. I don't think this is enough of a pain at this point to bother.
