### ISSUE TITLE
[Mod] Twilight Forest

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#164]
**Name:** Twilight Forest
**Short desc:** This is one we have had in the past.
**Adds to world gen:** no
**Link:** https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest

I don't know that I am ready to add this to the pack just yet. But it could be fun for later down the road.

**Comment by moshner** [comment]
I'm good with this now. The pack might need some more questing stuff
