### ISSUE TITLE
Heart of diamond to diamond

### ISSUE THREAD

**Issue by moshner** [worldofpannotia/minecraft-modpack#173]
I would like to see a way to convert hearts of diamond into something more useful. After we have the books and spawn eggs we need there isn't much we can use the heart of diamonds for. Could we add a smelting recipe that turns one heart of diamond into either diamond or raw diamond? 

It's really underpowered that way given how hard it is to find stonelings so it won't make a huge balance change to the game. If you want to REALLY underpowered it we could also consider letting it smelt down into a few chunks of diamond as well. I'd be good with 4-6 chunks of diamond.

OOOO! What if it had to be put through the crushing wheels in create to get 6-12 chunks of diamond! That way we have more automations we can build and more fun is had!

**Comment by moshner** [comment]
we could even add a by-product like heart containers or spirit orbs to represent the living nature of these diamonds.

**Comment by chimericdream** [comment]
I like the sound of that. Especially adding more variety to what we can do with Create.
