### ISSUE TITLE
If items are put in a bundle they disappear

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#190]
**Pack Version:** 13.0.0-ht-alpha.2
**Mod Name:** Easy Shulker Boxes

**Describe the bug**
When items are put into a bundle, they are instead deleted.

**To Reproduce**
1. Get a bundle
2. Right click on some items to put them in the bundle
3. Put the bundle back into your inventory
4. See the bundle revert to "empty"

**Expected behavior**
Items don't get deleted

**Additional context**
It looks like this is a bug in the third-party mod, [Easy Shulker Boxes](https://github.com/Fuzss/easyshulkerboxes/issues/19). I will keep this ticket open as a reminder to re-add ESB once the bug is fixed.

**Comment by Leronus** [comment]
Can confirm bug is still present

**Comment by chimericdream** [comment]
The bug is present in a third-party mod that we have removed from the pack for now. This ticket is only open as a way to flag the bug so that when it gets fixed, we can re-add the mod.
