### ISSUE TITLE
Spawn eggs with no AI

### ISSUE THREAD

**Issue by chimericdream** [worldofpannotia/minecraft-modpack#90]
Link: https://www.curseforge.com/minecraft/mc-mods/no-ai-spawn-eggs

This could be fun to use in conjunction with aesthetic builds. It would allow for things like "passive" versions (basically statues) of hostile mobs like the creeper.

**Comment by moshner** [comment]
Do you still want this in 8.0?

**Comment by chimericdream** [comment]
I'm up in the air. On the one hand, it could be fun. On the other... eh. That said, since the Spawner Control mod makes it easier (trivial?) to obtain mob eggs, maybe we just add a way to convert a regular mob egg to one with no AI. That way it still requires some work to acquire, and we don't run into potential issues where you could just craft whatever eggs you want, throw them in an empty spawner, and go to town with some crazy mob farm (does the wither have a spawn egg? 😛).

**Comment by moshner** [comment]
Could be fun. What would this do to our lag?

**Comment by chimericdream** [comment]
They would be entities, but they would be stationary. I don't think it would have a significant impact, but we could always test it.
